### ISSUE TITLE
[feat]pls check hosts.yaml

### ISSUE THREAD

**Issue by Cyber-SiKu** [opencurve/curveadm#213]
no host
```bash
curveadm host commit hosts.yaml
curveadm host ls
```
![eeb60eaead0783ccac97d53310c0c73](https://user-images.githubusercontent.com/15775037/234192204-5fe4928b-1f62-4473-8aaf-cfdb50cad4de.png)

no global in hosts.yaml
pls add some check in `curveadm hosts commit`

**Comment by Xinlong-Chen** [comment]
the hosts.yaml should be like this format:

```yaml
global:
  user: curve
  ssh_port: 22
  private_key_file: /home/curve/.ssh/id_rsa

hosts:
  - host: server-host1
    hostname: 10.0.1.1
```

but after copy, it would take some error(it is illegal):

```yaml
  user: curve
  ssh_port: 22
  private_key_file: /home/curve/.ssh/id_rsa

hosts:
  - host: server-host1
    hostname: 10.0.1.1
```

if we run command, it will also success:

```shell
curveadm host commit hosts.yaml
``` 

we wish curveadm can earlier exposure of problems. it is necessary to find problems in time.
