### ISSUE TITLE
curveadm playbook deploy memcached

### ISSUE THREAD

**Issue by Cyber-SiKu** [opencurve/curveadm#240]
[deploy_memcached](https:·//github.com/opencurve/curveadm/wiki/deploy_memcached)

目前，部署memcahced 一个服务就要对应一个host，修改起来繁琐，可以对这方面进行优化，使得对一台机器部署多个服务时仅需要修改一个host即可。
---
At present, deploying a memcahced service requires corresponding to a host, which is cumbersome to modify. This aspect can be optimized so that only one host needs to be modified when deploying multiple services on a machine.

**Comment by 0fatal** [comment]
hi, I'm a student majoring in software engineering in hdu, who is interested in distributed system. I'm good at golang and javascript. Familiar at kubernetes and linux, I wish to contribute to this task.

**Comment by EricWai** [comment]
Hello, I am a student from UESTC. I am good at golang language. I have learned k8s related knowledge and am interested in this issue.
I think a good solution is to reformat the yaml files. In current versions, deploying multiple services on a single host(10.0.1.1) requires the following configuration in hosts.yaml:
```
- host: server-host1
  hostname: 10.0.1.1
  labels:
    - memcached
  envs:
    - IMAGE=memcached:1.6.17
    - LISTEN=10.0.1.1
    ...

- host: server-host2
  hostname: 10.0.1.1
  labels:
    - memcached
  envs:
    - IMAGE=memcached:1.6.17
    - LISTEN=10.0.1.1
    ...
```

I think it can be modified as:
```
- host: server-host1
  hostname: 10.0.1.1
  - servername: server1
    labels:
      - memcached
    envs:
      - IMAGE=memcached:1.6.17
      - LISTEN=10.0.1.1
      ...

  - servername: server1
    labels:
      - memcached
    envs:
      - IMAGE=memcached:1.6.17
      - LISTEN=10.0.1.1
      ...
```
so that only one host needs to be modified when deploying multiple services on a machine.

**I hope the task will be assigned to me！**

**Comment by Cyber-SiKu** [comment]
> Hello, I am a student from UESTC. I am good at golang language. I have learned k8s related knowledge and am interested in this issue. I think a good solution is to reformat the yaml files. In current versions, deploying multiple services on a single host(10.0.1.1) requires the following configuration in hosts.yaml:
> 
> ```
> - host: server-host1
>   hostname: 10.0.1.1
>   labels:
>     - memcached
>   envs:
>     - IMAGE=memcached:1.6.17
>     - LISTEN=10.0.1.1
>     ...
> 
> - host: server-host2
>   hostname: 10.0.1.1
>   labels:
>     - memcached
>   envs:
>     - IMAGE=memcached:1.6.17
>     - LISTEN=10.0.1.1
>     ...
> ```
> 
> I think it can be modified as:
> 
> ```
> - host: server-host1
>   hostname: 10.0.1.1
>   - servername: server1
>     labels:
>       - memcached
>     envs:
>       - IMAGE=memcached:1.6.17
>       - LISTEN=10.0.1.1
>       ...
> 
>   - servername: server1
>     labels:
>       - memcached
>     envs:
>       - IMAGE=memcached:1.6.17
>       - LISTEN=10.0.1.1
>       ...
> ```
> 
> so that only one host needs to be modified when deploying multiple services on a machine.
> 
> **I hope the task will be assigned to me！**

In this case, you also need to write a lot of configuration files. You can refer to the design of [topology's replica](https://github.com/opencurve/curveadm/wiki/curvebs-cluster-deployment). Add ${service_replica_sequence} to the port and file location. to distinguish.

**Comment by EricWai** [comment]
Thanks to guidance, the code has been modified to support replicas and ${replicas_sequence}. Now, when deploying the memcached cluster, hosts.yaml can be written as follows：
```
global:
  user: curve
  ssh_port: 22
  private_key_file: /home/curve/.ssh/id_rsa
  
hosts:
  - host: server-host1
    hostname: 10.0.1.1
    labels:
      - memcached
    envs:
      - SUDO_ALIAS=sudo
      - ENGINE=docker
      - IMAGE=memcached:1.6.17
      - EXPORTER_IMAGE=quay.io/prometheus/memcached-exporter:v0.13.0
      - LISTEN=10.0.1.1
      - PORT=1121${replicas_sequence}
      - EXPORTER_PORT=915${replicas_sequence}
      - USER=root
      - MEMORY_LIMIT=32768 # item memory in megabytes
      - MAX_ITEM_SIZE=8m # adjusts max item size (default: 1m, min: 1k, max: 1024m)
      - EXT_PATH=/mnt/memcachefile/cachefile:102${replicas_sequence}G
      - EXT_WBUF_SIZE=8 # size in megabytes of page write buffers.
      - EXT_ITEM_AGE=1 # store items idle at least this long (seconds, default: no age limit)
      - VERBOSE="v"
    replicas: 3

  - host: server-host2
    hostname: 10.0.1.2
    labels:
      - memcached
    envs:
      - SUDO_ALIAS=sudo
      - ENGINE=docker
      - IMAGE=memcached:1.6.17
      - EXPORTER_IMAGE=quay.io/prometheus/memcached-exporter:v0.13.0
      - LISTEN=10.0.1.2
      - PORT=11211
      - EXPORTER_PORT=9151
      - USER=root
      - MEMORY_LIMIT=32768 # item memory in megabytes
      - MAX_ITEM_SIZE=8m # adjusts max item size (default: 1m, min: 1k, max: 1024m)
      - EXT_PATH=/mnt/memcachefile/cachefile:102${replicas_sequence}G
      - EXT_WBUF_SIZE=8 # size in megabytes of page write buffers.
      - EXT_ITEM_AGE=1 # store items idle at least this long (seconds, default: no age limit)
      - VERBOSE="v"
```
