### ISSUE TITLE
[Improve] host and hostname

### ISSUE THREAD

**Issue by Wine93** [opencurve/curveadm#260]
目前我们主机管理模块中的 `host` 与 `hostname` 的命名容易让用户感到困扰，请帮助我们改进它，以提供更清晰易懂的配置项。特别需要注意的是，你需要兼容之前的配置。如果你有任何疑问或者建议，都可以在此 issue 下留言。

```yaml
lobal:
  user: curve
  ssh_port: 22
  private_key_file: /home/curve/.ssh/id_rsa

hosts:
  - host: server-host1
    hostname: 10.0.1.1
  - host: server-host2
    hostname: 10.0.1.2
  - host: server-host3
    hostname: 10.0.1.3
```
